name: automerge
on:
  pull_request:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Use Custom Action
        uses: victorvmaciel/app@main
